# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   labels:
#     environment: test
#   name: test
# spec:
#   replicas: 1
#   selector:
#     matchlabels:
#       environment: test
#   template:
#     metadata:
#       labels:
#         environment: test
#     spec:
#       containers:
#       - image: nginx:1.16
#         name: nginx

apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 2
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.7.9
        ports:
        - containerPort: 80